create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = timezone('utc', now());
    return new;
end;
$$;

create table if not exists public.planning_non_work_days (
    id bigint generated by default as identity primary key,
    module_id text not null,
    off_date date not null,
    label text,
    is_active boolean not null default true,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now()),
    constraint planning_non_work_days_module_date_key unique (module_id, off_date)
);

alter table public.planning_non_work_days
    add column if not exists module_id text,
    add column if not exists off_date date,
    add column if not exists label text,
    add column if not exists is_active boolean not null default true,
    add column if not exists created_at timestamptz not null default timezone('utc', now()),
    add column if not exists updated_at timestamptz not null default timezone('utc', now());

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'planning_non_work_days_module_date_key'
          and conrelid = 'public.planning_non_work_days'::regclass
    ) then
        alter table public.planning_non_work_days
            add constraint planning_non_work_days_module_date_key unique (module_id, off_date);
    end if;
end;
$$;

do $$
begin
    if not exists (
        select 1
        from pg_trigger
        where tgname = 'trg_planning_non_work_days_updated_at'
          and tgrelid = 'public.planning_non_work_days'::regclass
    ) then
        create trigger trg_planning_non_work_days_updated_at
        before update on public.planning_non_work_days
        for each row execute function public.set_updated_at();
    end if;
end;
$$;
