-- ================================================================
-- Migration 58: Production Issue drafts stored per user
-- ================================================================
--
-- Unfinished "Report Issue" forms used to be kept only in the browser
-- (localStorage), so a user's drafts existed only on the PC where they were
-- typed. This table keeps each user's drafts with their account, so they
-- follow the user to any device. Each user only ever reads their own rows
-- (the app filters by user_email); drafts are never shown to anyone else.
--
-- Safe for the current app/: nothing reads this table until the new code is
-- deployed, and the new code falls back to browser-only drafts if it's missing.

create table if not exists public.production_issue_drafts (
    id          text primary key,              -- generated by the app
    user_email  text not null,
    module      text not null,                 -- kd1 / kd2 / f100kd2
    data        jsonb not null,                -- the form fields
    updated_at  timestamptz not null default timezone('utc', now())
);

create index if not exists idx_production_issue_drafts_user
    on public.production_issue_drafts (user_email, module);

-- Same access model as production_issues (migration 32) until the SC-01
-- security rebuild replaces it with per-user policies.
alter table public.production_issue_drafts enable row level security;

drop policy if exists "allow_all_authenticated" on public.production_issue_drafts;
create policy "allow_all_authenticated"
    on public.production_issue_drafts
    for all
    using (true)
    with check (true);
